ecomprj/core/urls.py
from django.urls import path, include
from core.views import index, contact, ajax_contact, create_checkout_session, payment_details, delete_from_wishlist, payment_result, liqpay_callback, add_to_wishlist, wishlist, make_address_default, order_detail, customer_dashboard, payment_completed, payment_failed, checkout, update_cart, delete_item_from_cart, search, cart, add_to_cart, ajax_add_review, filter_products, product_list, category_list, category_product_list, vendor_list, vendor_details, products_detail, tag_list
from core import views

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('products/', product_list, name='product-list'),
    path('product/<pid>/', products_detail, name='product-detail'),

    path('category/', category_list, name='category-list'),
    path('category/<cid>/', category_product_list, name='category-product-list'),

    path('vendors/', vendor_list, name='vendor-list'),
    path('vendor/<vid>/', vendor_details, name='vendor-details'),

    path('products/tag/<slug:tag_slug>/', tag_list, name='tags'),
    path('search/', search, name='search'),

    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),

    path('filter-products/', filter_products, name='filter-products'),

    # filter product
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('cart/', cart, name='cart'),

    path('delete-from-cart/', delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', update_cart, name='update-cart'),

    path('checkout/<oid>/', checkout, name='checkout'),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-failed/<str:oid>/', payment_failed, name='payment-failed'),
    path('payment-completed/<oid>/', payment_completed, name='payment-completed'),

    path('dashboard/', customer_dashboard, name='dashboard'),

    path('dashboard/order/<int:id>', order_detail, name='order-detail'),

    path("make-default-address/", make_address_default, name="make-default-address"),

    path("wishlist/", wishlist, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("delete-from-wishlist/", delete_from_wishlist, name="delete-from-wishlist"),

    # other urls
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact, name="ajax-contact-form"),

    # new Route
    path("save_checkout_info/", views.save_checkout_info, name="save_checkout_info"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),

    path('payment-details/<oid>/', payment_details, name='payment-details'),

    path('create-checkout-session/<str:oid>/', create_checkout_session, name='create_checkout_session'),
    path('payment-completed/<str:oid>/', payment_completed, name='payment-completed'),
    path('billing/pay-callback/', liqpay_callback, name='liqpay_callback'),

    path('payment-result/<str:oid>/', payment_result, name='payment-result'),

    path('verify_mfa/', views.verify_mfa, name='verify_mfa'),
    path('disable-2fa/', views.disable_2fa, name='disable_2fa'),
]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
    path('useradmin/', include('useradmin.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/templates/lfiles/lcheckout.html
{%  extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="../core/index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop
                    <span></span> Checkout
                </div>
            </div>
        </div>
        <div class="container mb-80 mt-50">
            <div class="row">
                <div class="col-lg-8 mb-40">
                    <h1 class="heading-2 mb-10">Checkout</h1>
                    <div class="d-flex justify-content-between">
                        <h6 class="text-body">There are <span class="text-brand">{{ totalcartitems }}</span> product{{ totalcartitems|pluralize }} in your cart</h6>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-7">
                    <div class="row mb-50">
                        <div class="col-lg-6">
                            <form method="post" class="apply-coupon">
                                <input type="text" placeholder="Enter Coupon Code...">
                                <button class="btn  btn-md" name="login">Apply Coupon</button>
                            </form>
                        </div>
                    </div>
                    <div class="row">
                        <h4 class="mb-30">Billing Details</h4>
                        <form method="post">
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="fname" value='{{request.user.username|title}}'  placeholder="First name *">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input type="text" required="" name="lname" value='{{active_address.mobile}}' placeholder="Mobile *">
                                </div>
                            </div>
                            <div class="row">
                                <div class="form-group col-lg-6">
                                    <input type="text" name="billing_address" value='{{active_address.address}}' required="" placeholder="Address *">
                                </div>
                                <div class="form-group col-lg-6">
                                    <input type="text" name="billing_address2" required="" value='{{active_address.address}}' placeholder="Address line2">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="col-lg-5">
                    <div class="border p-40 cart-totals ml-30 mb-50">
                        <div class="d-flex align-items-end justify-content-between mb-30">
                            <h4>Your Order</h4>
                            <h6 class="text-muted">Subtotal - <span class="red-text">${{ cart_total|floatformat:2 }}</span></h6>
                        </div>
                        <div class="divider-2 mb-30"></div>
                        <a href="{% url 'core:cart' %}" class="btn btn-fill-out btn-block mt-30 mb-40">Go back to Cart<i class="fi-rs-sign-in ml-15"></i></a>
                        <div class="table-responsive order_table checkout">
                            <table class="table no-border">
                                <tbody>
                                {% for product_id, item in cart_data.items %}
                                    <tr>
                                        <td class="image product-thumbnail"><img src="{{ item.image }}" alt="#"></td>
                                        <td>
                                            <h6 class="w-160 mb-5"><a href="{% url 'core:product-detail' item.pid %}" class="text-heading">{{ item.title }}</a></h6></span>
                                        </td>
                                        <td>
                                            <h6 class="text-muted pl-20 pr-20">x {{ item.quantity }}</h6>
                                        </td>
                                        <td>
                                            <h5 class="text-muted">${{ item.price }}</h5>
                                        </td>
                                        <td>
                                            <h4 class="text-brand">${% widthratio item.price 1 item.quantity %}</h4>
                                        </td>
                                    </tr>
                                {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="payment ml-30">
                        <h4 class="mb-30">Payment</h4>
                        <div class="payment_option">
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios3" checked="">
                                <label class="form-check-label" for="exampleRadios3" data-bs-toggle="collapse" data-target="#bankTranfer" aria-controls="bankTranfer">Direct Bank Transfer</label>
                            </div>
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios4" checked="">
                                <label class="form-check-label" for="exampleRadios4" data-bs-toggle="collapse" data-target="#checkPayment" aria-controls="checkPayment">Cash on delivery</label>
                            </div>
                            <div class="custome-radio">
                                <input class="form-check-input" required="" type="radio" name="payment_option" id="exampleRadios5" checked="">
                                <label class="form-check-label" for="exampleRadios5" data-bs-toggle="collapse" data-target="#paypal" aria-controls="paypal">Online Getway</label>
                            </div>
                        </div>
                        <div class="payment-logo d-flex">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-paypal.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-visa.svg' %}" alt="">
                            <img class="mr-15" src="{% static 'assets/imgs/theme/icons/payment-master.svg' %}" alt="">
                            <img src="{% static 'assets/imgs/theme/icons/payment-zapper.svg' %}" alt="">
                        <div class="w-50">
                            {{ paypal_payment_button.render }}
                        </div>
<!--                        <a href="#" class="btn btn-fill-out btn-block mt-30">Place an Order<i class="fi-rs-sign-out ml-15"></i></a>-->
                </div>
            </div>
        </div>
    </main>
{% endblock %}