ecomprj/core/urls.py
from django.urls import path, include
from core.views import index, contact, ajax_contact, create_checkout_session, payment_details, delete_from_wishlist, payment_result, liqpay_callback, add_to_wishlist, wishlist, make_address_default, order_detail, customer_dashboard, payment_completed, payment_failed, checkout, update_cart, delete_item_from_cart, search, cart, add_to_cart, ajax_add_review, filter_products, product_list, category_list, category_product_list, vendor_list, vendor_details, products_detail, tag_list
from core import views

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
    path('products/', product_list, name='product-list'),
    path('product/<pid>/', products_detail, name='product-detail'),

    path('category/', category_list, name='category-list'),
    path('category/<cid>/', category_product_list, name='category-product-list'),

    path('vendors/', vendor_list, name='vendor-list'),
    path('vendor/<vid>/', vendor_details, name='vendor-details'),

    path('products/tag/<slug:tag_slug>/', tag_list, name='tags'),
    path('search/', search, name='search'),

    path('ajax-add-review/<int:pid>/', ajax_add_review, name='ajax-add-review'),

    path('filter-products/', filter_products, name='filter-products'),

    # filter product
    path('add-to-cart/', add_to_cart, name='add-to-cart'),
    path('cart/', cart, name='cart'),

    path('delete-from-cart/', delete_item_from_cart, name='delete-from-cart'),
    path('update-cart/', update_cart, name='update-cart'),

    path('checkout/<oid>/', checkout, name='checkout'),

    path('paypal/', include('paypal.standard.ipn.urls')),
    path('payment-failed/<str:oid>/', payment_failed, name='payment-failed'),
    path('payment-completed/<oid>/', payment_completed, name='payment-completed'),

    path('dashboard/', customer_dashboard, name='dashboard'),

    path('dashboard/order/<int:id>', order_detail, name='order-detail'),

    path("make-default-address/", make_address_default, name="make-default-address"),

    path("wishlist/", wishlist, name="wishlist"),
    path("add-to-wishlist/", add_to_wishlist, name="add-to-wishlist"),
    path("delete-from-wishlist/", delete_from_wishlist, name="delete-from-wishlist"),

    # other urls
    path("contact/", contact, name="contact"),
    path("ajax-contact-form/", ajax_contact, name="ajax-contact-form"),

    # new Route
    path("save_checkout_info/", views.save_checkout_info, name="save_checkout_info"),
    path("api/create_checkout_session/<oid>/", create_checkout_session, name="api_checkout_session"),

    path('payment-details/<oid>/', payment_details, name='payment-details'),

    path('create-checkout-session/<str:oid>/', create_checkout_session, name='create_checkout_session'),
    path('payment-completed/<str:oid>/', payment_completed, name='payment-completed'),
    path('billing/pay-callback/', liqpay_callback, name='liqpay_callback'),

    path('payment-result/<str:oid>/', payment_result, name='payment-result'),

    path('verify_mfa/', views.verify_mfa, name='verify_mfa'),
    path('disable-2fa/', views.disable_2fa, name='disable_2fa'),
]

ecomprj/ecomprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('user/', include('userauths.urls')),
    path('useradmin/', include('useradmin.urls')),

    path('ckeditor/', include('ckeditor_uploader.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecomprj/core/forms.py
from django import forms
from core.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Write review'}))

    class Meta:
        model = ProductReview
        fields = ['review', 'rating']

ecomprj/core/views.py
from django.shortcuts import render, get_object_or_404, redirect
from taggit.models import Tag
from core.models import Category, Tags, Vendor, Coupon, Product, ProductImages, CartOrder, CartOrderItems, ProductReview, WishList, Address
from userauths.models import ContactUs, Profile, User
from core.forms import ProductReviewForm
from django.http import JsonResponse, HttpResponse
from django.template.loader import render_to_string
from django.contrib import messages
from django.conf import settings
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from paypal.standard.forms import PayPalPaymentsForm
from django.core import serializers
from django.views.generic import TemplateView, View
from django.utils.decorators import method_decorator

import calendar
from django.db.models import Count, Avg
from django.db.models.functions import ExtractMonth, ExtractYear
import stripe
from liqpay.liqpay import LiqPay
import base64
import hashlib
import json

import io
import pyotp
import qrcode
from django.contrib.auth import login


def index(request):
    # products = Product.objects.all().order_by('-id')
    products = Product.objects.filter(product_status='published', featured=True)

    context = {
        'products': products,
    }
    return render(request, 'core/index.html', context)


def product_list(request):
    products = Product.objects.filter(product_status='published')

    context = {
        'products': products,
    }
    return render(request, 'core/product-list.html', context)


def category_list(request):
    # categories = Category.objects.all()
    categories = Category.objects.all().annotate(product_count=Count('category'))

    context = {
        'categories': categories,
    }
    return render(request, 'core/category-list.html', context)


def category_product_list(request, cid):
    category = Category.objects.get(cid=cid)
    products = Product.objects.filter(product_status='published', category=category)

    context = {
        'category': category,
        'products': products,
    }
    return render(request, 'core/category-product-list.html', context)


def vendor_list(request):
    vendors = Vendor.objects.all()

    context = {
        'vendors': vendors,
    }
    return render(request, 'core/vendor-list.html', context)


def vendor_details(request, vid):
    vendor = Vendor.objects.get(vid=vid)
    products = Product.objects.filter(product_status='published', vendor=vendor)

    context = {
        'vendor': vendor,
        'products': products,
    }
    return render(request, 'core/vendor-details.html', context)


def products_detail(request, pid):
    product = Product.objects.get(pid=pid)
    # product = get_object_or_404(Product, pid=pid)
    products = Product.objects.filter(category=product.category).exclude(pid=pid)[:4]

    # getting reviews
    reviews = ProductReview.objects.filter(product=product).order_by('-date')

    # getting average reviews related to products
    average_rating = ProductReview.objects.filter(product=product).aggregate(rating=Avg('rating'))

    # product review form
    review_form = ProductReviewForm

    make_review = True
    if request.user.is_authenticated:
        user_review_count = ProductReview.objects.filter(user=request.user, product=product).count()

        if user_review_count > 0:
            make_review = False

    p_image = product.p_images.all()

    context = {
        'product': product,
        'reviews': reviews,
        'review_form': review_form,
        'make_review': make_review,
        'average_rating': average_rating,
        'p_image': p_image,
        'products': products,
    }
    return render(request, 'core/product-detail.html', context)


def tag_list(request, tag_slug=None):
    products = Product.objects.filter(product_status='published').order_by('-id')
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        products = products.filter(tags__in=[tag])

    context = {
        'products': products,
        'tag': tag,
    }
    return render(request, 'core/tag.html', context)


def ajax_add_review(request, pid):
    product = Product.objects.get(pk=pid)
    user = request.user

    review = ProductReview.objects.create(
        user=user,
        product=product,
        review=request.POST['review'],
        rating=request.POST['rating'],
    )

    context = {
        'user': user.username,
        'review': request.POST['review'],
        'rating': request.POST['rating'],
    }

    average_reviews = ProductReview.objects.filter(product=product).aggregate(rating=Avg("rating"))

    return JsonResponse(
       {
        'bool': True,
        'context': context,
        'average_reviews': average_reviews
       }
    )


def search(request):
    query = request.GET.get("query")

    products = Product.objects.filter(title__icontains=query).order_by("-date")

    context = {
        "products": products,
        "query": query,
    }
    return render(request, "core/search.html", context)


def filter_products(request):
    categories = request.GET.getlist('category[]')
    vendors = request.GET.getlist('vendor[]')

    min_price = request.GET['min_price']
    max_price = request.GET['max_price']

    products = Product.objects.filter(product_status='published').order_by('-date').distinct()

    products = products.filter(price__gte=min_price)
    products = products.filter(price__lte=max_price)

    if len(categories) > 0:
        products = products.filter(category__id__in=categories).distinct()

    if len(vendors) > 0:
        products = products.filter(vendor__id__in=vendors).distinct()

    data = render_to_string('core/async/product-list.html', {'products': products})
    return JsonResponse({'data': data})


def add_to_cart(request):
    cart_product = {}

    cart_product[str(request.GET['id'])] = {
        'title': request.GET['title'],
        'quantity': request.GET['quantity'],
        'price': request.GET['price'],
        'image': request.GET['image'],
        'pid': request.GET['pid'],
    }

    if 'cart_data_obj' in request.session:
        if str(request.GET['id']) in request.session['cart_data_obj']:

            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity'] = int(cart_product[str(request.GET['id'])]['quantity'])
            cart_data.update(cart_data)
            request.session['cart_data_obj'] = cart_data
        else:
            cart_data = request.session['cart_data_obj']
            cart_data.update(cart_product)
            request.session['cart_data_obj'] = cart_data
    else:
        request.session['cart_data_obj'] = cart_product
    return JsonResponse({"data": request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj'])})


def cart(request):
    cart_total = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total += float(item['price']) * int(item['quantity'])
        return render(request, 'core/cart.html', {'cart_data': request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total': cart_total})

    else:
        messages.warning(request, 'Your cart is empty')
        return redirect('core:index')


def delete_item_from_cart(request):
    product_id = str(request.GET['id'])
    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            del request.session['cart_data_obj'][product_id]
            request.session['cart_data_obj'] = cart_data

    cart_total = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total += float(item['price']) * int(item['quantity'])

    context = render_to_string('core/async/cart-list.html', {'cart_data': request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total': cart_total})
    return JsonResponse({'data': context, 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total': cart_total})


def update_cart(request):
    product_id = str(request.GET['id'])
    product_quantity = request.GET['quantity']

    if 'cart_data_obj' in request.session:
        if product_id in request.session['cart_data_obj']:
            cart_data = request.session['cart_data_obj']
            cart_data[str(request.GET['id'])]['quantity'] = product_quantity
            request.session['cart_data_obj'] = cart_data

    cart_total = 0
    if 'cart_data_obj' in request.session:
        for product_id, item in request.session['cart_data_obj'].items():
            cart_total += float(item['price']) * int(item['quantity'])

    context = render_to_string('core/async/cart-list.html', {'cart_data': request.session['cart_data_obj'], 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total': cart_total})
    return JsonResponse({'data': context, 'totalcartitems': len(request.session['cart_data_obj']), 'cart_total': cart_total})


def save_checkout_info(request):
    cart_total = 0
    total_amount = 0

    if request.method == 'POST':
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        mobile = request.POST.get('mobile')
        address = request.POST.get('address')
        city = request.POST.get('city')
        state = request.POST.get('state')
        country = request.POST.get('country')

        request.session['full_name'] = full_name
        request.session['email'] = email
        request.session['mobile'] = mobile
        request.session['address'] = address
        request.session['city'] = city
        request.session['state'] = state
        request.session['country'] = country

        if 'cart_data_obj' in request.session:

ecomprj/templates/core/payment-completed.html
{%  extends 'partials/base.html' %}
{% load static %}
{% block content %}

<div class="row justify-content-center pt-lg-4 text-center" style="margin-bottom: 200px; margin-top: 100px;">
    <div class="col-lg-5 col-md-7 col-sm-9">
        <h1 class="display-404 py-lg-3">Payment Completed</h1>
        <h2 class="h3 mb-4">Your order has been successfully placed. Order Id #{{order.oid}}</h2>
        <p class="fs-md mb-4">
            <a href="#">Contact us</a> if you have any issue or question
        </p>
        <p>
            <a class="button-details" href="{% url 'core:payment-details' order.oid %}"><i></i>Details</a>
        </p>
    </div>
</div>

{% endblock %}

ecomprj/templates/core/payment-failed.html
{%  extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main page-404">
        <div class="page-content pt-150 pb-150">
            <div class="container">
                <div class="row">
                    <div class="col-xl-8 col-lg-10 col-md-12 m-auto text-center">
                        <p class="mb-20"><img src="{% static 'assets/imgs/cross.png' %}" alt="" class="hover-up" /></p>
                        <h1 class="display-2 mb-30">Payment Failed</h1>
                        <p class="font-lg text-grey-700 mb-30">
                            Try Again Later
                        </p>

                        <a class="btn btn-default submit-auto-width font-xs hover-up mt-30" href="{% url 'core:index' %}"><i class="fi-rs-home mr-5"></i> Back To Home Page</a>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}

ecomprj/templates/core/vendor-list.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
    <!--End header-->
    <main class="main pages mb-80">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Vendors List
                </div>
            </div>
        </div>
        <div class="page-content pt-50">
            <div class="container">
                <div class="archive-header-2 text-center">
                    <h1 class="display-2 mb-50">Vendors List</h1>
                    <div class="row">
                        <div class="col-lg-5 mx-auto">
                            <div class="sidebar-widget-2 widget_search mb-50">
                                <div class="search-form">
                                    <form action="#">
                                        <input type="text" placeholder="Search vendors (by name or ID)..." />
                                        <button type="submit"><i class="fi-rs-search"></i></button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row mb-50">
                    <div class="col-12 col-lg-8 mx-auto">
                        <div class="shop-product-fillter">
                            <div class="totall-product">
                                <p>We have <strong class="text-brand">{{vendors.count}}</strong> vendor{{vendors.count|pluralize}} now</p>
                            </div>
                            <div class="sort-by-product-area">
                                <div class="sort-by-cover mr-10">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps"></i>Show:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> 50 <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">50</a></li>
                                            <li><a href="#">100</a></li>
                                            <li><a href="#">150</a></li>
                                            <li><a href="#">200</a></li>
                                            <li><a href="#">All</a></li>
                                        </ul>
                                    </div>
                                </div>
                                <div class="sort-by-cover">
                                    <div class="sort-by-product-wrap">
                                        <div class="sort-by">
                                            <span><i class="fi-rs-apps-sort"></i>Sort by:</span>
                                        </div>
                                        <div class="sort-by-dropdown-wrap">
                                            <span> Featured <i class="fi-rs-angle-small-down"></i></span>
                                        </div>
                                    </div>
                                    <div class="sort-by-dropdown">
                                        <ul>
                                            <li><a class="active" href="#">Mall</a></li>
                                            <li><a href="#">Featured</a></li>
                                            <li><a href="#">Preferred</a></li>
                                            <li><a href="#">Total items</a></li>
                                            <li><a href="#">Avg. Rating</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row vendor-grid">
                    {% for vendor in vendors %}
                    <div class="col-lg-6 col-md-6 col-12 col-sm-6">
                        <div class="vendor-wrap style-2 mb-40">
                            <div class="product-badges product-badges-position product-badges-mrg">
                                <!-- <span class="hot">Mall</span> -->
                            </div>
                            <div class="vendor-img-action-wrap">
                                <div class="vendor-img">
                                    <a href="{% url 'core:vendor-details' vendor.vid %}">
                                        <img class="default-img" src="{{vendor.image.url}}" alt="" />
                                    </a>
                                </div>
                                <div class="mt-10">
                                    <span class="font-small total-product">{{vendor.product.all.count}} Products</span>
                                </div>
                            </div>
                            <div class="vendor-content-wrap">
                                <div class="mb-30">
                                    <div class="product-category">
                                        <span class="text-muted">Since {{vendor.date|date:"Y"}}</span>
                                    </div>
                                    <h4 class="mb-5"><a href="{% url 'core:vendor-details' vendor.vid %}">{{vendor.title}}</a></h4>
                                    <div class="product-rate-cover">
                                        <div class="product-rate d-inline-block">
                                            <div class="product-rating" style="width: 90%"></div>
                                        </div>
                                        <span class="font-small ml-5 text-muted"> (4.0)</span>
                                    </div>
                                    <div class="vendor-info d-flex justify-content-between align-items-end mt-30">
                                        <ul class="contact-infor text-muted">
                                            <li><img src="assets/imgs/theme/icons/icon-location.svg" alt="" /><strong>Address: </strong> <span>{{vendor.address}}</span></li>
                                            <li><img src="assets/imgs/theme/icons/icon-contact.svg" alt="" /><strong>Call Us:</strong><span>{{vendor.contact}}</span></li>
                                        </ul>
                                        <br>
                                    </div>
                                    <br>
                                    <a href="{% url 'core:vendor-details' vendor.vid %}" class="btn btn-xs">Visit Store <i class="fi-rs-arrow-small-right"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                <div class="pagination-area mt-20 mb-20">
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-start">
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-left"></i></a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item"><a class="page-link dot" href="#">...</a></li>
                            <li class="page-item"><a class="page-link" href="#">6</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#"><i class="fi-rs-arrow-small-right"></i></a>
                            </li>
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </main>

    {% endblock %}

ecomprj/templates/core/wishlist.html
{%  extends 'partials/base.html' %}
{% load static %}
{% block content %}

    <main class="main" id="wishlist-list">
        <div class="page-header breadcrumb-wrap">
            <div class="container">
                <div class="breadcrumb">
                    <a href="index.html" rel="nofollow"><i class="fi-rs-home mr-5"></i>Home</a>
                    <span></span> Shop <span></span> Fillter
                </div>
            </div>
        </div>
        <div class="container mb-30 mt-50">
            <div class="row">
                <div class="col-xl-10 col-lg-12 m-auto">
                    <div class="mb-50">
                        <h1 class="heading-2 mb-10">Your Wishlist</h1>
                        <h6 class="text-body">There are <span class="text-brand count-items">{{  wishlist_count }}</span> product{{  wishlist_count|pluralize }} in this list</h6>
                    </div>
                    <div class="table-responsive shopping-summery">
                        <table class="table table-wishlist">
                            <thead>
                                <tr class="main-heading">
                                    <th class="custome-checkbox start pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox11" value="" />
                                        <label class="form-check-label" for="exampleCheckbox11"></label>
                                    </th>
                                    <th scope="col" colspan="2">Product</th>
                                    <th scope="col">Price</th>
                                    <th scope="col">Stock Status</th>
                                    <th scope="col">Action</th>
                                    <th scope="col" class="end">Remove</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for wishlist in wishlist %}

                                <tr class="pt-30">
                                    <td class="custome-checkbox pl-30">
                                        <input class="form-check-input" type="checkbox" name="checkbox" id="exampleCheckbox1" value="" />
                                        <label class="form-check-label" for="exampleCheckbox1"></label>
                                    </td>
                                    <td class="image product-thumbnail pt-40"><img src="{{ wishlist.product.image.url }}" alt="#" /></td>
                                    <td class="product-des product-name">
                                        <h6><a class="product-name mb-10" href="{% url 'core:product-detail' wishlist.product.pid  %}">{{ wishlist.product.title|truncatechars:30 }}</a></h6>
                                    </td>
                                    <td class="price " data-title="Price">
                                        <h4 class="text-brand">
                                            <span>$</span>
                                            <span class="current-product-price-{{ wishlist.product.id }}">{{ wishlist.product.price }}</span>
                                        </h4>
                                    </td>
                                    <td class="text-left detail-info" data-title="Stock">
                                        <span class="stock-status mb-0 {% if wishlist.product.in_stock %} in-stock {% else %} out-stock {% endif %}">
                                            {% if wishlist.product.in_stock %} In Stock {% else %} Out of Stock {% endif %}
                                        </span>
                                    </td>
                                    <td class="text-right" data-title="Cart">

                                        <input type="hidden" value="1" id="product-quantity" class="product-quantity-{{ wishlist.product.id }}">
                                        <input type="hidden" class="product-pid-{{ wishlist.product.id }}" value="{{ wishlist.product.pid }}">
                                        <input type="hidden" class="product-image-{{  wishlist.product.id }}" value="{{ wishlist.product.image.url }}">
                                        <input type="hidden" class="product-id-{{ wishlist.product.id }}" value="{{ wishlist.product.id }}">
                                        <input type="hidden" class="product-title-{{ wishlist.product.id }}" value="{{ wishlist.product.title }}">

                                        <button class="btn btn-sm add add-to-cart-btn" data-index="{{ wishlist.product.id }}">Add to cart</button>
                                    </td>
                                    <td class="action text-center" data-title="Remove">
                                        <button style="border : none; background: none" data-wishlist-product="{{ wishlist.id }}" class="text-body delete-wishlist-product"><i class="fi-rs-trash"></i></button>
                                    </td>
                                </tr>
                            {% empty %}
                            <tr>
                                <td><p>Nothing in wishlist yet.</p></td>
                            </tr>
                            {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </main>

{% endblock %}